import React from 'react';
import ReactDOM from 'react-dom/client';
import { HashRouter, Routes, Route, Link, useParams, Navigate, useNavigate } from 'react-router-dom';
import { motion, useReducedMotion } from 'framer-motion';
import './styles.css';

type P={slug:string,index:string,title:string,kicker:string,description:string,tracks:string[],stack:string[],role:string,system:string,built:string[],observed:string[],learned:string[],github?:string,accent:string};
const projects:P[]=[
{slug:'soc-homelab-splunk',index:'01',title:'SOC HOMELAB / SPLUNK',kicker:'attack → telemetry → detection → investigation',description:'A small SOC environment for generating suspicious activity, collecting telemetry, writing detections and tracing what actually happened.',tracks:['SOC','Detection','Windows'],stack:['Splunk','Windows Events','Linux','Sigma','MITRE ATT&CK'],role:'Detection / Investigation',system:'Windows → Events → Splunk → Detection → Triage',built:['Windows and Linux endpoints producing realistic security telemetry.','Splunk searches for suspicious authentication and endpoint activity.','Investigation flow from alert to event correlation and triage.'],observed:['Authentication anomalies become useful when identity, host and time context are correlated.','Single events rarely tell the full story; sequences and baselines matter.'],learned:['Detection quality depends on understanding the system generating the logs.','Good rules should support investigation, not just fire alerts.'],github:'https://github.com/BinNguyen-Sec/SOC-Homelab-Splunk',accent:'red'},
{slug:'bincorp-enterprise-infrastructure',index:'02',title:'BINCORP / ENTERPRISE INFRASTRUCTURE',kicker:'network → identity → endpoint → monitoring',description:'An enterprise-style lab where networking, Active Directory, PKI, endpoint security and monitoring are treated as one system.',tracks:['Network','Identity','Security'],stack:['Active Directory','Windows Server','pfSense','PKI','VPN','Suricata','Splunk'],role:'Infrastructure / Security Architecture',system:'Network → Identity → Endpoint → Security Telemetry',built:['Segmented enterprise network with Windows domain services.','Identity services, PKI, policy controls and secure remote access.','Monitoring and IDS visibility across infrastructure layers.'],observed:['Security problems become easier to reason about when network and identity context are visible together.','Misconfiguration creates attack paths long before an exploit is involved.'],learned:['Infrastructure design is part of security design.','Identity, segmentation and telemetry should be planned together.'],github:'https://github.com/BinNguyen-Sec/bincorp-enterprise-infrastructure-lab',accent:'blue'},
{slug:'threat-hunting-detection',index:'03',title:'THREAT HUNTING / DETECTION',kicker:'timeline → correlation → MITRE → detection',description:'A detection engineering workflow centered on timeline building, event correlation, MITRE mapping, triage and reusable Sigma detections.',tracks:['Threat Hunting','Detection','IR'],stack:['Windows Events','Splunk','Sigma','MITRE ATT&CK'],role:'Threat Hunting / Detection Engineering',system:'Telemetry → Timeline → Correlation → Triage → Detection',built:['Investigation timeline around simulated attacker activity.','Correlation queries connecting endpoint and identity evidence.','Sigma detections derived from confirmed behavioral patterns.'],observed:['Detection engineering works best when rules are derived from investigation evidence.','MITRE ATT&CK is useful as a map, not a substitute for event-level reasoning.'],learned:['A strong hunt ends with a clearer detection hypothesis.','Triage should explain why an event is suspicious, not just label it suspicious.'],accent:'violet'},
{slug:'cloud-assignment-system',index:'04',title:'CLOUD ASSIGNMENT SYSTEM',kicker:'application → container → cloud → delivery → monitoring',description:'A university assignment that evolved into a containerized cloud application with CI/CD, identity federation, HTTPS, load balancing and monitoring.',tracks:['Cloud','DevSecOps','Application'],stack:['AWS','Docker','.NET','GitHub Actions','OIDC','ALB','CloudWatch'],role:'Cloud / Delivery',system:'App → Container → CI/CD → AWS → Monitoring',built:['Containerized .NET application and deployment workflow.','GitHub Actions with OIDC-based AWS authentication.','Load-balanced HTTPS environment with CloudWatch monitoring.'],observed:['Cloud security depends heavily on identity and deployment design.','CI/CD is infrastructure and therefore part of the attack surface.'],learned:['Prefer short-lived identity federation over long-lived cloud secrets.','Production readiness includes observability, HTTPS and failure handling.'],github:'https://github.com/BinNguyen-Sec/cloud-assignment-system-v3',accent:'off'}];

const more=[['05','Binh Minh Enterprise Network','physical design → VLANs → redundancy → WAN → validation'],['06','Zero Trust Endpoint Security','posture → identity → VPN → policy → enforcement']];
const Reveal=({children}:{children:React.ReactNode})=>{const r=useReducedMotion();return r?<>{children}</>:<motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.6}}>{children}</motion.div>};
const Resume=()=> <a className="resume" href="/resume/Nguyen-Ngoc-Khai-Resume.pdf" download><b>↓</b><span>DOWNLOAD RESUME<small>PDF / ENGLISH</small></span></a>;
const Header=()=> {const navigate=useNavigate();const go=(id:string)=>{navigate('/');window.setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}),80)};return <header><Link to="/" className="brand">BINNGUYEN-SEC</Link><nav><button onClick={()=>go('work')}>WORK</button><button onClick={()=>go('system')}>SYSTEM</button><button onClick={()=>go('contact')}>CONTACT</button></nav></header>};
const Signal=()=> <div className="signal"><span>TRACE / LIVE</span><i><b className="p1"/><b className="p2"/><b className="p3"/></i><span>AUTH / 4769</span></div>;
function Home(){return <><Header/><main><section className="hero"><div><div className="eyebrow">BIN / NGUYEN — HCMC / VN</div><h1>CYBERSECURITY<span>SOC / NETWORK SECURITY / IDENTITY</span></h1><p className="statement">I build systems to understand<br/>how they fail —<br/><em>and what they leave behind.</em></p><div className="actions"><Resume/><button className="textlink" onClick={()=>document.getElementById('work')?.scrollIntoView({behavior:'smooth'})}>VIEW SELECTED WORK ↓</button></div></div><aside className="readout"><p><span>AVAILABILITY</span><strong>INTERNSHIP</strong></p><p><span>TRACK</span><strong>SOC / NETWORK SECURITY</strong></p><p><span>LOCATION</span><strong>HCMC / VN</strong></p><p><span>AUTH</span><strong className="red">4769</strong></p><p><span>TRACE</span><strong className="blue">ACTIVE</strong></p><p><span>STATUS</span><strong className="violet">INVESTIGATING_</strong></p></aside></section><Signal/>
<section className="section"><Reveal><div className="eyebrow">01 / ABOUT</div><div className="about"><h2>I learn infrastructure by building it, breaking assumptions, and tracing what happened next.</h2><div className="readout"><p><span>FOCUS</span><strong>SOC / Network Security</strong></p><p><span>CURRENT</span><strong>CCNA / AD / Detection</strong></p><p><span>METHOD</span><strong>build → break → observe → understand</strong></p><p><span>LOCATION</span><strong>Ho Chi Minh City</strong></p></div></div></Reveal></section>
<section id="work" className="section"><div className="eyebrow">02 / SELECTED WORK</div><h2 className="mega">PROJECTS THAT LEFT<br/>USEFUL EVIDENCE.</h2>{projects.map(p=><Reveal key={p.slug}><article className={'project '+p.accent}><div className="projectmeta"><span>{p.index} / SELECTED WORK</span><span>{p.tracks.join(' / ')}</span></div><div className="projectbody"><div><h3>{p.title}</h3><p className="kicker">{p.kicker}</p><p className="desc">{p.description}</p><div className="tags">{p.stack.slice(0,5).map(x=><span key={x}>{x}</span>)}</div></div><div className="visual"><div className="bigindex">{p.index}</div><div className="trace">EVENT <strong>{p.index==='01'?'4769':'0'+p.index+'17'}</strong></div></div></div><Link className="case" to={'/work/'+p.slug}>VIEW CASE STUDY ↗</Link></article></Reveal>)}</section>
<section id="system" className="section"><Reveal><div className="eyebrow">03 / SYSTEMS I KEEP TOUCHING</div><div className="systems">{[['NETWORK','Cisco / VLAN / STP / OSPF / VPN / pfSense'],['IDENTITY','Active Directory / Kerberos / PKI / GPO'],['DETECTION','Splunk / Sigma / Windows Events / Suricata'],['INFRASTRUCTURE','Windows Server / VMware / Linux / AWS'],['SCRIPTING','PowerShell / Python / C# / .NET']].map(([a,b])=><article key={a}><span>{a}</span><p>{b}</p></article>)}</div></Reveal></section>
<section className="section"><Reveal><div className="eyebrow">04 / CURRENT SIGNAL</div><div className="current">{[['LEARNING','Kerberos / AD Security / Detection Engineering'],['BUILDING','Portfolio / Public Proof'],['CERT','CCNA — in progress'],['NEXT','TryHackMe SOC Level 1']].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></Reveal></section>
<section className="section"><Reveal><div className="eyebrow">05 / MORE WORK</div>{more.map(([i,t,l])=><div className="more" key={t}><span>{i}</span><h3>{t}</h3><p>{l}</p></div>)}</Reveal></section>
<section className="section cta"><Reveal><div className="eyebrow">06 / RESUME</div><h2 className="mega">LOOKING FOR A<br/>CYBERSECURITY INTERN?</h2><p>Selected work is above. The concise version is one click away.</p><Resume/></Reveal></section></main><footer id="contact" className="section"><div className="eyebrow">07 / CONTACT</div><h2 className="mega">LET'S TRACE<br/>SOMETHING.</h2><Resume/><div className="footerlinks"><a href="https://github.com/BinNguyen-Sec" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/ngockhai-sec/" target="_blank">LinkedIn ↗</a><a href="mailto:ngockhai.sec@gmail.com">Email ↗</a></div><div className="footbottom"><span>SYSTEMS / IDENTITY / DETECTION</span><span>build things. break things. understand why.</span></div></footer></>}
function Detail(){const {slug}=useParams();const p=projects.find(x=>x.slug===slug);if(!p)return <Navigate to="/404"/>;return <><Header/><main className="detail section"><Link className="back" to="/">← BACK / SELECTED WORK</Link><div className="eyebrow">{p.index} / CASE STUDY</div><h1>{p.title}</h1><p className="kicker">{p.kicker}</p><div className="detailmeta"><p><span>ROLE</span><strong>{p.role}</strong></p><p><span>SYSTEM</span><strong>{p.system}</strong></p><p><span>TRACK</span><strong>{p.tracks.join(' / ')}</strong></p></div><div className="casegrid">{[['WHAT I BUILT',p.built],['WHAT I OBSERVED',p.observed],['WHAT I LEARNED',p.learned]].map(([t,arr])=><Reveal key={t as string}><div className="eyebrow">{t as string}</div><ul>{(arr as string[]).map(v=><li key={v}>{v}</li>)}</ul></Reveal>)}</div><div className="eyebrow">SYSTEM TRACE</div><div className="arch">{p.system.split(' → ').map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong>{i<p.system.split(' → ').length-1&&<i>→</i>}</div>)}</div><section className="caseend"><h2 className="mega">PROOF OVER CLAIMS.</h2>{p.github?<a className="resume compact" href={p.github} target="_blank">VIEW SOURCE ↗</a>:<span className="muted">Repository documentation in progress.</span>}</section></main></>}
function NotFound(){return <><Header/><main className="nf"><div className="eyebrow">404 / TRACE LOST</div><h1>NOTHING<br/>RESPONDED.</h1><p>The path exists only in theory.</p><Link className="resume compact" to="/">RETURN HOME ←</Link></main></>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/work/:slug" element={<Detail/>}/><Route path="/404" element={<NotFound/>}/><Route path="*" element={<NotFound/>}/></Routes>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><HashRouter><App/></HashRouter></React.StrictMode>);
